### ISSUE TITLE
Missing checkbox function

### ISSUE THREAD

**Issue by mrmagic2020** [Basssiiie/OpenRCT2-FlexUI#30]
**Describe the bug**
The latest version of openrct2-flexui seems to be missing the `checkbox` function.

**To reproduce**
1. Run `npm install openrct2-flexui` in your project.
2. Import `checkbox`:
``` ts
import {
  window, checkbox
} from "openrct2-flexui";
```

**Expected behavior**
Shown in the screenshot.

**Screenshots**
<img width="606" alt="Screen Shot 2023-05-03 at 4 49 50 pm" src="https://user-images.githubusercontent.com/104749673/235848691-85d6fab0-c5ac-4ed2-9e22-eb089bafcc71.png">
<img width="985" alt="Screen Shot 2023-05-03 at 4 52 05 pm" src="https://user-images.githubusercontent.com/104749673/235849095-d5c97127-a90f-4efa-9714-74e979b113cd.png">
The function is not exported in `node_modules/openrct2-flexui/dist/index.d.ts` file.

**Comment by Basssiiie** [comment]
Hey there, make sure you run `npm install openrct2-flexui@next` as outlined in the readme. The `@next` is important, otherwise you'll install an older prerelease (the oldest one I think). :)

Though, I really should fix sometime that `@latest` also refers to the last prerelease too.

**Comment by mrmagic2020** [comment]
> Hey there, make sure you run `npm install openrct2-flexui@next` as outlined in the readme. The `@next` is important, otherwise you'll install an older prerelease (the oldest one I think). :)
> 
> Though, I really should fix sometime that `@latest` also refers to the last prerelease too.

Yep, all fixed =)
