### ISSUE TITLE
Calling WindowTemplate close method fires BaseWindowParams onClose function twice

### ISSUE THREAD

**Issue by Alfinch** [Basssiiie/OpenRCT2-FlexUI#32]
**Describe the bug**
When programmatically closing a window, if an onClose handler is set, it is called twice.

**To reproduce**
A very simple example of this issue:
```typescript
const w = window({
    title: "Test window",
    content: [
        button({ text: "Close", height: 21, onClick: () => w.close() }),
    ],
    height: "auto",
    width: 100,
    onClose: () => console.log("Closed test window"),
});
w.open();
```
When the "Close" button is clicked, "Closed test window" is logged to the console twice.

**Expected behavior**
OnClose should be called once when a window is closed programmatically.

Because onClose is a convenient place to put cleanup code, calling this handler twice can result in issues with disposing already disposed objects, null references where objects have been removed etc.

**Comment by Basssiiie** [comment]
Hey thank you for reporting this! I'll look into it later this week. 🙂

**Comment by Alfinch** [comment]
No problem! Quite easy to work around, but figured you'd appreciate knowing.

**Comment by Basssiiie** [comment]
@Alfinch Much appreciated indeed. A fix is now available in pre-release 16. Thanks for letting me know! 😄

**Comment by Alfinch** [comment]
Thanks for the speedy fix! Really appreciated.
