### ISSUE TITLE
Add native support for custom (graphics context-based) widgets

### ISSUE THREAD

**Issue by ltsSmitty** [Basssiiie/OpenRCT2-FlexUI#33]
**Add support for a custom() widget**
The current implementation doesn't offer a corresponding `custom` type widget with an `onDraw` method. I see there's a `widget()` exposed, but it has no bindings, so it doesn't seem to fit the bill.

**Potential options**
1. Export the `Control` class to users. This would let users create a lookalike to the similar `ButtonControl`, `DropdownControl`, etc. I tested this by making a custom local build of FlexUI this way, just adding the `Control` export, and have made a nice custom widget component using just that. Check out [my implementation](https://github.com/ltsSmitty/OpenRCT-drawing/blob/main/src/window/customWidget.ts) if you're curious. (The user also needs to know to create their own WidgetBaseDesc, since the .d.ts in the flexui package isn't in sync with the one released by OpenRCT2 (as of 0.4.10).) For example:

      ```ts
      interface WidgetBaseDesc extends Omit<WidgetBase, "window"> {}
      ```

2. I'm happy to submit a PR adding this custom widget as a native flexui widget, to correspond to OpenRCT2's `custom` type. I'm not sure how to name it though - the other widgets are one word, but calling it `custom` feels too vague. Potentially something like  `customWidget` or  `customDraw`? 
3. Perhaps there's already a way to do this using the unbound `widget` that I'm not aware of.

**Comment by Basssiiie** [comment]
Thank you for your feature request! What bindings would you need for the custom widget? The custom widget should be possible with `widget()`, which basically works as a pass-through to OpenRCT2's API, though I was planning to add the custom widget (and any other missing widgets) at some point yes. Maybe naming it `graphics()` or something similar would be more representative of what it's actually for.

As for exposing the `Control` class, maybe some day I may expose it. Though, as I've still got a few features in mind I wanna build, I don't want to risk breaking a lot of code dependant on the exposed class. Generally I try to limit breakage of public api's while optimizing internal api's like I see fit. Exposing the control class will prevent me from doing that on this core component, so I think it's better to expose it after all the major features I would want to have are in.

Also yes I should update openrct2.d.ts, I didn't realise it was that outdated. 😅 Though the user should really bring their own openrct2.d.ts and not rely on the one FlexUI uses (is it even in the FlexUI package?).

**Comment by ltsSmitty** [comment]
My specific issue with the graphics context is that the `onDraw` requires a `this` as this first argument, and I wasn't sure how to access it via the widget. Is there a way to do that? Just trying to use `this` gave me a bunch of complaints and I wasn't sure what to try next, hence me trying to make a new native graphics widget.
