### ISSUE TITLE
Dropdown widget ignores initial selected index

### ISSUE THREAD

**Issue by Alfinch** [Basssiiie/OpenRCT2-FlexUI#35]
**Describe the bug**
When opening a new window with a dropdown widget, the dropdown is always initialised with the first item selected. If selectedIndex is set to an index other than 0 before the window is created, it will immediately be set to 0.

This doesn't match the behaviour of other widgets, which do seem to respect initial values (i.e. ColourPickerParams.color, CheckboxParams.checked, SpinnerParams.value etc.)

**To reproduce**
Example:
```typescript
  const items = store(["Item 1", "Item 2", "Item 3"]);
  const selectedIndex = store(1); // Item 2

  selectedIndex.subscribe((index) => {
    console.log(index);
  });

  const w = window({
    title: "Test",
    width: 280,
    height: "auto",
    content: [
      dropdown({
        items: items,
        selectedIndex: twoway(selectedIndex),
      }),
    ],
  });
  w.open();
```
The window opens with "Item 1" selected.
Console output is "0", indicating the dropdown widget has written 0 to the store.

**Expected behavior**
When a valid selectedIndex is specified, the dropdown should be initialised with the correct item pre-selected.

**Comment by Basssiiie** [comment]
Hey, thank you for your bug report. I can reproduce this and this is indeed not expected behaviour. I'm gonna look into this. 🙂

**Comment by Basssiiie** [comment]
@Alfinch The bug has been fixed and an updated package has been pushed to NPM. Thanks again for reporting! 🙂

**Comment by Alfinch** [comment]
No worries - thanks again for the quick fix!
