### ISSUE TITLE
Allow `listview` to programmatically change the `selectedCell`

### ISSUE THREAD

**Issue by KatieZeldaKat** [Basssiiie/OpenRCT2-FlexUI#36]
**Idea**
Give `listview` a parameter for `selectedCell`, allowing initialization of a selection or resetting to not select anything. By default, nothing would be selected (current behavior).

**Additional context**
The `openrct2.d.ts` file has a `selectedCell` parameter for `ListViewDesc` and `ListViewWidget`, so I don't believe this feature would require any additional changes to OpenRCT2 itself.

Ideally, when calling `listview`, FlexUI would define a parameter `selectedCell?: Bindable<RowColumn | null>`, so that a window can better change what is currently selected, and even deselect by setting to null.

**Comment by Basssiiie** [comment]
Hey KatieZeldaKat, thank you for your suggestion! I think it's a good idea and I'm surprised it's not supported yet. I think it should be quite easy to add as well. It might even be possible to make it a two-way bindable by including the `onClick` event. 

I'll try to have a look at it when I have some time, or maybe someone else can pick it up if they want. 🙂

**Comment by Basssiiie** [comment]
@KatieZeldaKat @mrmagic2020 FlexUI pre-release 19 has been pushed to NPM with this new property. 😀
